apiVersion: v1
kind: Service
metadata:
  name: flaskapp
  labels:
    app: flaskapp
    version: v1
spec:
  selector:
    app: flaskapp
    version: v1
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
spec:
  selector:
     matchLabels:
      app: flaskapp
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapp
        version: v1
    spec:
      containers:
      - name: flaskapp
        image: flaskdemoxdli:v1
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 80
        env:
        - name: test1
          value: "50"
        - name: test2
          value: "200"
        - name: version
          value: "v1"